version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform:
- Win32
- x64
init:
- ps: 
install:
- ps: >-
    Push-Location "Quetoo.vs15\"

    [Environment]::CurrentDirectory = $PWD

    .\PREPARE_ALL.ps1

    Pop-Location

    [Environment]::CurrentDirectory = $PWD

    md -Path "..\Objectively"

    Push-Location "..\Objectively\"

    [Environment]::CurrentDirectory = $PWD

    (New-Object System.Net.WebClient).DownloadFile("https://ci.appveyor.com/api/projects/Paril/objectively/artifacts/__dep.zip?job=Platform%3A+" + $env:PLATFORM, "tmp.zip")

    7z x tmp.zip -aos "*"

    Remove-Item "tmp.*"

    Pop-Location

    [Environment]::CurrentDirectory = $PWD

    md -Path "..\ObjectivelyMVC"

    Push-Location "..\ObjectivelyMVC\"

    [Environment]::CurrentDirectory = $PWD

    (New-Object System.Net.WebClient).DownloadFile("https://ci.appveyor.com/api/projects/Paril/objectivelymvc/artifacts/__dep.zip?job=Platform%3A+" + $env:PLATFORM, "tmp.zip")

    7z x tmp.zip -aos "*"

    Remove-Item "tmp.*"

    Pop-Location

    [Environment]::CurrentDirectory = $PWD
build:
  parallel: false
  verbosity: minimal
  project: Quetoo.vs15\quetoo.sln
after_build:
- ps: >-
    Push-Location "Quetoo.vs15\"

    [Environment]::CurrentDirectory = $PWD

    Remove-Item .\Quetoo\* -include *.exp,*.lib,*.ilk -recurse

    7z a ..\Quetoo-BETA-MSVC.zip Quetoo\

    Pop-Location

    [Environment]::CurrentDirectory = $PWD
test: off
artifacts:
- path: Quetoo-BETA-MSVC.zip
on_finish:
- ps:  >-
    Push-Location "Quetoo.vs15\"

    [Environment]::CurrentDirectory = $PWD

    .\SYNC.ps1

    .\AWS.ps1

    Pop-Location

    [Environment]::CurrentDirectory = $PWD
deploy: off
cache:
  - Quetoo.vs15\libs\curses\tmp.zip -> appveyor.yml
  - Quetoo.vs15\libs\glib\include\tmp.tar.xz -> appveyor.yml
  - Quetoo.vs15\libs\physfs\tmp.tar.bz2 -> appveyor.yml
  - Quetoo.vs15\libs\sdl_mixer\SDL2\tmp.zip -> appveyor.yml
  - Quetoo.vs15\libs\xml\include\tmp.tar.gz -> appveyor.yml